### ISSUE TITLE
Compiling doesn't work in the latest update

### ISSUE THREAD

**Issue by Codeguyross** [tombh/total-viewsheds#1]
The make file is broken and doesn't download the files properly. I manually went and added the external libraries one at a time, however, building the project fails during the tests. Here is the error:

../src/BOS.cpp:89:32: error: expected expression
  sort(idx.begin(), idx.end(), [&v](size_t i1, size_t i2) { return v[i1] < v[i2]; });
                               ^

Full output for reference:
13:27:41 **** Incremental Build of configuration Default for project testing ****
make all 
Building file: ../test/axes_test.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/axes_test.d" -MT"test/axes_test.o" -o "test/axes_test.o" "../test/axes_test.cpp"
Finished building: ../test/axes_test.cpp
 
Building file: ../test/basic_viewshed_tests.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/basic_viewshed_tests.d" -MT"test/basic_viewshed_tests.o" -o "test/basic_viewshed_tests.o" "../test/basic_viewshed_tests.cpp"
Finished building: ../test/basic_viewshed_tests.cpp
 
Building file: ../test/bos_test.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/bos_test.d" -MT"test/bos_test.o" -o "test/bos_test.o" "../test/bos_test.cpp"
Finished building: ../test/bos_test.cpp
 
Building file: ../test/dem_tests.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/dem_tests.d" -MT"test/dem_tests.o" -o "test/dem_tests.o" "../test/dem_tests.cpp"
Finished building: ../test/dem_tests.cpp
 
Building file: ../test/gpu_viewsheds_tests.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/gpu_viewsheds_tests.d" -MT"test/gpu_viewsheds_tests.o" -o "test/gpu_viewsheds_tests.o" "../test/gpu_viewsheds_tests.cpp"
Finished building: ../test/gpu_viewsheds_tests.cpp
 
Building file: ../test/helper.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/helper.d" -MT"test/helper.o" -o "test/helper.o" "../test/helper.cpp"
Finished building: ../test/helper.cpp
 
Building file: ../test/main.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/main.d" -MT"test/main.o" -o "test/main.o" "../test/main.cpp"
Finished building: ../test/main.cpp
 
Building file: ../test/total_viewshed_tests.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"test/total_viewshed_tests.d" -MT"test/total_viewshed_tests.o" -o "test/total_viewshed_tests.o" "../test/total_viewshed_tests.cpp"
Finished building: ../test/total_viewshed_tests.cpp
 
Building file: ../src/Axes.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Axes.d" -MT"src/Axes.o" -o "src/Axes.o" "../src/Axes.cpp"
Finished building: ../src/Axes.cpp
 
Building file: ../src/BOS.cpp
Invoking: GCC C++ Compiler
g++ -I"/Users/me/Downloads/total-viewsheds-master 2/include" -I"/Users/me/Downloads/total-viewsheds-master 2/include/gflags" -I"/Users/me/Downloads/total-viewsheds-master 2/include/plog" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"src/BOS.d" -MT"src/BOS.o" -o "src/BOS.o" "../src/BOS.cpp"
../src/BOS.cpp:89:32: error: expected expression
  sort(idx.begin(), idx.end(), [&v](size_t i1, size_t i2) { return v[i1] < v[i2]; });
                               ^
1 error generated.
make: *** [src/BOS.o] Error 1

13:27:54 Build Finished (took 12s.641ms)

**Comment by tombh** [comment]
Sorry for the delay. I'm really happy that you're having a go with this, you're the first I know of.

I still haven't had time to properly look into your problem, so I can only guess. Maybe you've downloaded a newer version of Plog then I pinned to in the `Makefile`? Can you see [all the git hashes](https://github.com/tombh/total-viewsheds/blob/master/Makefile#L89) here for the deps? Make sure you're checking out those versions.

But I'm surprised the `make` isn't doing that for you already. Can you paste the error for that? Or is it just silent?

**Comment by Codeguyross** [comment]
I am going to go try to find the versions that are listed in the make file and manually input the files in place and then I will provide the errors as I hit them. 

The following is a direct copy and paste of cloning and then calling make:

![image](https://user-images.githubusercontent.com/1108129/30545047-13ea4282-9c4e-11e7-9d0c-d5d77cc9e524.png)

**Comment by Codeguyross** [comment]
I went and cloned each repo individually. I then did a hard reset on the repo to the SHA provided in the makefile found in the home directory of total viewshed. In order to get past the plog not found I went into the include folder in the plog repo and copy and pasted the plog folder into the include folder inside total-viewshed which was created the first time I tried to run the makefile inside total-viewshed. 

![image](https://user-images.githubusercontent.com/1108129/30548008-93d7109e-9c56-11e7-8345-3f842628f7ce.png)

The first error here is from gflags needing to be built. Easy enough. I went into the gflags repo and typed 'cmake .' The make file in total-viewshed is trying to grab files that were generated in the include folder the was made from running cmake inside of gflags. I went ahead and copied the files generated from running cmake inside of gflags into the include folder in total viewshed.

The second error is showing problems with math functions inside Axes.cpp. The fix is to use 'include <cmath>' instead on 'include <math.h>. 

The next error that pops up is showing that 'include <CL/cl.hpp>' is not found.

This seems like a chain of issues related to the make file not working out of the box. I think the easiest solution would be a branch with everything included. I know I might need to build some things locally but there seems to be quit a few issues on this road

**Comment by Codeguyross** [comment]
I decided to get moving along and see if I could get this code compiled. Here are my results:
![image](https://user-images.githubusercontent.com/1108129/30562281-7c68ff1c-9c83-11e7-8e82-a495aa7d2532.png)
![image](https://user-images.githubusercontent.com/1108129/30562292-8414039c-9c83-11e7-91e5-c5c8661c4bf7.png)
![image](https://user-images.githubusercontent.com/1108129/30562295-884fa556-9c83-11e7-9438-c365207316f2.png)
![image](https://user-images.githubusercontent.com/1108129/30562302-904a95ae-9c83-11e7-9818-d94af9daa478.png)
![image](https://user-images.githubusercontent.com/1108129/30562305-95fb2ebe-9c83-11e7-943d-4b7fa169e2a5.png)

**Comment by Codeguyross** [comment]
I think this should help anyone will building this code so this issue can be closed
